# Change these first
owner: jaybhattcscgfm # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository
assignees:
  - JayBhatt
sites:
  - name: ViewPoint Prod
    url: https://viewpoint.cscgfm.com
  - name: Investran Web API - Reference Data
    url: https://investranweb-liveuat-eu.fiscloudservices.com/api/referencedata/v1/swagger/index.html

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**CSCGFM Status Page**"
  introMessage: >
    This status page monitors critical services like ViewPoint and Investran Web API. 
    Any outages or disruptions will be tracked in real-time using GitHub Actions and Upptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/jaybhattcscgfm/upptime


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
