# Change these first
owner: upptime # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: ViewPoint Prod
    url: https://viewpoint.cscgfm.com
  - name: Investran Web API - Reference Data
    url: https://investranweb-liveuat-eu.fiscloudservices.com/api/referencedata/v1/swagger/index.html
  - name: Fake Site
    url: https://thisdoesnotexist.example

status-website:
  apiBaseUrl: https://jaybhattcscgfm.github.io/upptime
  baseUrl: upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
